import Head from 'next/head';
import React from 'react'
import iconb from "../../public/images/svgexport-14.svg"
import Image from 'next/image';
import Link from 'next/link';

const otp = () => {
  return (
    <>
     <Head>
      <title>OTP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className='bg-sign flex justify-center items-center pt-20 pb-20'>
           <div className='bg-[white] h-[790px] w-[43%] shadow-lg shadow-black rounded-3xl'>
            <div className='mt-[14px] ml-[13px]'>
             <Image src={iconb} alt='logo' width={210}></Image>
            </div>
            <h2 className='text-[32px] font-apple font-lighter mt-[8px] ml-[75px] text-[#220C60]'>Sign In</h2>
            <p className='mt-[8px] ml-[75px] text-[18px] text-[#757576] font-apple font-medium'>Welcome back😜</p>
            <div className='ml-[75px] mt-[38px]'>
              <label htmlFor="Email" className='block text-[14px] text-[#67656E] font-apple font-medium'>Email</label>
              <input type="email" className='w-[85%] h-[50px] bg-[#F3F3F3] rounded-[4px] focus:outline-[#623ECA] hover:border-[2px] pl-2'/>
              <label htmlFor="Password" className='block text-[14px] text-[#67656E] font-apple font-medium mt-5'>Password</label>
              <input type="password" className='w-[85%] h-[50px] bg-[#F3F3F3] rounded-[4px] focus:outline-[#623ECA] hover:border-[2px] pl-2'/>
              <button className='block mt-[35px] w-[85%] h-[55px] bg-[#623ECA] rounded-[4px] text-[#FFFFFF] text-[18px] font-semibold font-sans'>Sign In</button>
            </div>
            <div className='flex items-center justify-center mt-10'>
              <span className='text-[18px] font-normal'>Do not have an account? <Link href='' className='font-semibold'>Signup</Link></span>
            </div>
              <p className='text-center mt-[27px] text-[14px]'>Avanin 1.0</p>
           </div>
        </section>
      </main>
    </>
  )
}

export default otp