import Head from 'next/head';
import React from 'react'
import iconb from "../../public/images/svgexport-14.svg"
import Image from 'next/image';
import Link from 'next/link';
const signup = () => {
  return (
    <>
      <Head>
      <title>Signup to Vividpay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className='bg-sign flex justify-center items-center pt-20 pb-20'>
           <div className='bg-[white] h-[790px] w-[43%] shadow-lg shadow-black rounded-3xl'>
            <div className='mt-[14px] ml-[13px]'>
             <Image src={iconb} alt='logo' width={210}></Image>
            </div>
            <h2 className='text-[32px] font-apple font-lighter mt-[8px] ml-[75px] text-[#220C60]'>Get started</h2>
            <p className='mt-[8px] ml-[75px] text-[18px] text-[#757576] font-apple font-medium'>Hi there, We welcome you to vividpay</p>
            <div className='ml-[75px] mt-[38px]'>
              <label htmlFor="Firstname" className='block text-[14px] text-[#67656E] font-apple font-medium'>Firstname</label>
              <input type="text" className='w-[85%] h-[50px] bg-[#757576] rounded-[4px]'/>
              <label htmlFor="Lastname" className='block text-[14px] text-[#67656E] font-apple font-medium mt-5'>Lastname</label>
              <input type="text" className='w-[85%] h-[50px] bg-[#757576] rounded-[4px]'/>
              <label htmlFor="Email" className='block text-[14px] text-[#67656E] font-apple font-medium mt-5'>Email</label>
              <input type="email" className='w-[85%] h-[50px] bg-[#757576] rounded-[4px]'/>
              <button className='block mt-[35px] w-[85%] h-[55px] bg-[#3813A0] rounded-[4px] text-[#FFFFFF] text-[18px] font-semibold font-sans'>Proceed</button>
            </div>
            <div className='flex items-center justify-center mt-10'>
              <span className='text-[18px] font-normal'>Already have an account? <Link href='' className='font-semibold'>Login</Link></span>
            </div>
              <p className='text-center mt-[27px] text-[14px]'>Avanin 1.0</p>
           </div>
        </section>
      </main>
    </>
  )
}

export default signup;