import Head from 'next/head'
import Image from 'next/image'
import {  Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
import Link from 'next/link'
import React, {  useRef } from 'react'
import iconb from '../public/images/svgexport-14.svg'
import apple from '../public/images/svgexport-5.svg'
import playstore from '../public/images/svgexport-6.svg'
import first from '../public/images/svgexport-7.svg'
import second from '../public/images/svgexport-8.svg'
import third from '../public/images/svgexport-9.svg'
import fourth from '../public/images/svgexport-10.svg'
import fifth from '../public/images/svgexport-11.svg'
import six from "../public/images/svgexport-12.svg"
import icon from "../public/images/svgexport-190.svg"
import phoneIm from '../public/images/more-services-phone.webp'
import emqil from "../public/images/phone-service2.webp"
import airtime from "../public/images/phone-service1.webp"
import icon1 from "../public/images/svgexport-190.svg"
import icon2 from "../public/images/svgexport-18.svg"
import Footer from '@/components/products/footer/Footer'
export default function Home() {
  const hamburgerBtnRef = useRef<HTMLButtonElement>(null);
  const mobileMenuRef = useRef<HTMLDivElement>(null);
  const toggleMenu = () => {
    if (hamburgerBtnRef.current && mobileMenuRef.current) {
      mobileMenuRef.current.classList.toggle('hidden');
      mobileMenuRef.current.classList.toggle('flex');
      hamburgerBtnRef.current.classList.toggle('toggle-btn');
    }
  }
  return (
    <>
      <Head>
        <title>Vividpay-Not just another payment app.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Header section */}
      <header className='bg-[#FFF7F2] sticky top-0 w-[100%]'>
         <section className='flex justify-between items-center -ml-[50px] lg:ml-0'>
            <div>
                <Link href="/" passHref>
                <Image src={iconb} alt="hello" width={250} height={100}/>
                </Link>
            </div>
            <button id="hamburger-button" className="text-3xl right-2 md:hidden cursor-pointer relative w-8 h-8" ref={hamburgerBtnRef} onClick={()=>toggleMenu()}>
            <div className="bg-black w-8 h-1 rounded absolute top-4 -mt-0.5 transition-all duration-500 before:content-[''] before:h-1 before:absolute before:bg-black before:w-8 before:rounded before:transition-all before:duration-500  before:-translate-x-4 before:-translate-y-3 after:content-[''] after:h-1 after:absolute after:bg-black after:w-8 after:rounded after:transition-all after:duration-500 after:-translate-x-4 after:translate-y-3"></div>
            </button>
            <div className='lg:inline md:inline hidden'>
                <ul className='flex gap-[45px]'>
                    <li className='font-semi-bold text-xl hover:text-[#220C60]'><Link href='/#hero' passHref>Home</Link></li>
                    <li className='font-semi-bold text-xl hover:text-[#220C60]'><Link href='/#about' passHref>About-Us</Link></li>
                    <li className='font-semi-bold text-xl hover:text-[#220C60] cursor-pointer'><Link href='/#product' passHref>Products</Link></li>
                    <li className='font-semi-bold text-xl hover:text-[#220C60]'><Link href='/#faq' passHref>FAQ</Link></li>
                    <li className='font-semi-bold text-xl hover:text-[#220C60]'><Link href='/#contact' passHref>Contact-Us</Link></li>
                </ul>
            </div>
            <div className='mr-32 lg:inline md:inline hidden'>
              <Link href='/auth/signin'><button className='border font-[700] text-[#3813A0] rounded-md border-[#3813A0] w-[100px] h-[45px] mr-4'>Log in</button></Link>
              <Link href='/auth/signup'><button className='w-[100px] h-[45px] font-[700] bg-[#3813A0] hover:bg-[#220C60] rounded-md text-[white]'>Sign up</button></Link>
            </div>
            <section id="mobile-menu" className="absolute top-0 bg-[#FFF7F2] w-full flex-col justify-content-center origin-top animate-open-menu hidden" ref={mobileMenuRef}>
         {/* <!-- <button class="text-8xl self-end px-6"> &times;</button> --> */}
         <nav className="flex flex-col min-h-screen items-center py-8" aria-label="mobile">
          <Link href="#hero" className="w-full text-center py-6 hover:opacity-90" >Home</Link>
          <Link href="#about" className="w-full text-center py-6 hover:opacity-90" >About-us</Link>
          <Link href="#product" className="w-full text-center py-6 hover:opacity-90">Product</Link>
          <Link href="#faq" className="w-full text-center py-6 hover:opacity-90">FAQ</Link>
          <Link href="#contact" className="w-full text-center py-6 hover:opacity-90">Contact-Us</Link>
          <div className=''>
              <Link href='/auth/signin'><button className='border font-[700] text-[#3813A0] rounded-md border-[#3813A0] w-[90%] h-[45px] mr-4'>Log in</button></Link>
              <Link href='/auth/signup'><button className='w-[90%] mt-3 h-[45px] font-[700] bg-[#3813A0] hover:bg-[#220C60] rounded-md text-[white]'>Sign up</button></Link>
            </div>
         </nav>
       </section>
         </section>
      </header>
      <ul className='hidden bg-[#525254] text-[16px] rounded-sm pl-4 w-[140px] absolute top-[90px] z-10 left-[380px] font-semibold'>
                       <li className='mb-3 text-white'><Link href='/' passHref>Airtime to Cash</Link></li>
                       <li className='mb-3 text-white'><Link href='/' passHref>Cashpin</Link></li>
                       <li className='mb-3 text-white'><Link href='/' passHref>Virtual Card</Link></li>
                      </ul>
                      {/* Hero section */}
        <div className='lg:flex md:flex block bg-[#FFF7F2] pb-10' id='hero'>
       <div className='lg:w-1/2 md:w-1/2 w-full lg:pt-0 md:pt-0 pt-10'>
        <p className='font-apple lg:text-[30px] md:text-[30px] text-[25px] font-medium text-[#525254] lg:mt-20 md:mt-20 lg:ml-[89px] md:ml-[89px] text-center lg:text-justify md:text-justify'>The Most Unique Digital Wallet</p>
        <div className='lg:ml-[89px] md:ml-[89px] text-center lg:text-start md:text-start lg:text-[56px] md:text-[40px] text-[40px] font-bold text-[#220C60] mt-3 font-apple'>
        Not Just Another Payment App
        </div>
        <div className='lg:ml-[89px] md:ml-[89px] text-center lg:text-justify md:text-justify lg:text-[16px] md:text-[16px] text-[16px] font-apple font-normal lg:p-0 md:p-0 p-4'>
        We know everyone is tired of new payment apps, but what we have built is VERY UNIQUE. It is fresh, it is new, it is different. Tribapay is a digital wallet that lets you send and receive money, store money in a pin, sell your airtime and get cash, pay with your Dollar Card and pay for other utilities.
        </div>
        <div className='lg:ml-[89px] md:ml-[89px] flex text-center lg:text-justify md:text-justify p-6 lg:p-0 md:p-0 lg:mt-[28px] md:mt-[28px] mt-[0px]'>
          <Link href='/' passHref><Image src={apple} width={140} height={100} alt={"apple_stor"}></Image></Link>
          <Link href='/' passHref><Image src={playstore} width={140} height={100} alt={"apple_stor"} className="lg:ml-10 md:ml-10 ml-2"></Image></Link>
        </div>
       </div>
       <div className='lg:w-1/2 md:w-1/2 w-full'>
        <div className='lg:flex md:flex flex justify-center items-center lg:ml-60 md:ml-60 ml-0 mt-20'>
           <div className='rounded-lg w-[110px] h-[210px] lg:w-[150px] lg:h-[170px] shadow-2xl mr-7 bg-[#FBF5F0] transition-all duration-300 hover:scale-90'>
             <Image src={first} alt='' width={40} height={40} className='ml-3 mt-3'/>
             <p className='font-apple font-medium ml-3 mt-3 text-[#8E6704]'>Airtime to Cash</p>
             <div className='text-[13px] ml-3 mt-2 text-[rgb(82,82,84)]'>
              Sell your airtime and get cash and or buy airtime.
             </div>
           </div>
           <div className='rounded-lg w-[110px] h-[210px] lg:w-[150px] lg:h-[170px] shadow-2xl mr-7 bg-[#F7F6FC] transition-all duration-300 hover:scale-90'>
           <Image src={second} alt='' width={40} height={40} className='ml-3 mt-3'/>
             <p className='font-apple font-medium ml-3 mt-3 text-[#4317C0]'>Cashpin</p>
             <div className='text-[13px] ml-3 mt-2 text-[#525254]'>
              Cashpin is a token that can be saved as cash.
             </div>
           </div>
        </div>
        <div className='mt-6 lg:flex md:flex flex justify-center content-center lg:ml-60 md:ml-60 ml-0'>
           <div className='rounded-lg w-[110px] h-[210px] lg:w-[150px] lg:h-[170px] shadow-2xl mr-7 bg-[#FBF1F1] transition-all duration-300 hover:scale-90'>
           <Image src={third} alt='' width={40} height={40} className='ml-3 mt-3'/>
             <p className='font-apple font-medium ml-3 mt-3 text-[#C02634]'>Send Funds</p>
             <div className='text-[13px] ml-3 mt-2 text-[#525254]'>
              Send money to an email address or any bank accounts.
             </div>
           </div>
           <div className='rounded-lg w-[110px] h-[210px] lg:w-[150px] lg:h-[170px] shadow-2xl mr-7 bg-[#F0F7F4] transition-all duration-300 hover:scale-90'>
           <Image src={fourth} alt='' width={40} height={40} className='ml-3 mt-3'/>
             <p className='font-apple font-medium ml-3 mt-3 text-[#1E8A5E]'>Fund wallet</p>
             <div className='text-[13px] ml-3 mt-2 text-[#525254]'>
              Fund your vividpay wallet and send money to anyone.
             </div>
           </div>
        </div>
        <div className='mt-6 lg:flex md:flex flex justify-center items-center lg:ml-60 md:ml-60 ml-0'>
           <div className='rounded-lg w-[110px] h-[210px] lg:w-[150px] lg:h-[170px] shadow-2xl mr-7 bg-[#F1F4FB] transition-all duration-300 hover:scale-90'>
           <Image src={fifth} alt='' width={40} height={40} className='ml-3 mt-3'/>
             <p className='font-apple font-medium ml-3 mt-3 text-[#013AC0]'>Pay bills</p>
             <div className='text-[13px] ml-3 mt-2 text-[#525254]'>
              Pay electricity, TV subcription, data and more bills.
             </div>
           </div>
           <div className='rounded-lg w-[110px] h-[210px] lg:w-[150px] lg:h-[170px] shadow-2xl mr-7 bg-[#FEF5FF] transition-all duration-300 hover:scale-90'>
           <Image src={six} alt='' width={40} height={40} className='ml-3 mt-3'/>
             <p className='font-apple font-medium ml-3 mt-3 text-[#AE00BB]'>Get cards</p>
             <div className='text-[13px] ml-3 mt-2 text-[#525254]'>
              Get virtual Naira and dollar card in seconds.
             </div>
           </div>
        </div>
           <p className='lg:text-[30px] md:text-[25px] text-[18px] mt-4 font-bold text-[#E0E0E2] font-apple lg:ml-60 md:ml-60 ml-0 text-center lg:text-justify md:text-justify'>What Would You Like To Do?</p>
       </div>
      </div>
      {/* About-us section */}
      <div className='lg:flex md:flex block bg-new mt-20' id='about'>
      <div className='lg:ml-[100px] md:ml-[100px] ml-0 lg:text-justify md:text-justify text-center lg:w-1/2 md:w-1/2 w-full mt-28'>
        <div className='flex'>
        <hr className='bg-[#D9D1F2] w-[100px] h-[7px] mt-2 rounded'/><span className='text-[18px] font-bold ml-4 font-apple text-[#3734A9]'>About-Us</span>
        </div>
        <h1 className='lg:text-[48px] md:text-[48px] text-[30px] font-medium text-[#220C60] font-apple'>About Vividpay</h1>
        <p className='text-[16px] text-[#525254] font-normal mt-3'>Vividpay is a digital wallet that lets you send and receive money,<br/>store money in a pin, sell your airtime and get cash, pay with your <br/>Dollar Card and pay for other utilities.</p>
        <Link href='/auth/signup' passHref><div className='flex mt-6 w-[200px] h-[45px] font-[700] bg-[#3813A0] hover:bg-[#220C60] rounded-md
         text-[white] p-3 font-apple lg:ml-0 md:ml-0 ml-6'>
          <button className='mr-4'>Get Started</button><Image src={icon} alt='' className='w-auto transition-all duration-1000 hover:translate-x-6'></Image>
        </div></Link>
      </div>
      <div className='lg:w-1/2 md:w-1/2 w-full lg:mt-0 md:mt-0 mt-8 lg:text-justify md:text-justify text-center p-3'>
        <Image src={phoneIm} alt='' className='lg:w-[300px] md:w-[300px] w-auto'></Image>
      </div>
     </div>
        {/* Products-section */}
     <div className='lg:flex md:flex block bg-new mt-36 lg:p-0 md:p-0 p-2' id='product'>
        <div className='bg-[#FEF1F2] text-center pt-16 pl-16 pr-16 pb-0 rounded-[40px] lg:ml-[200px] md:ml-[200px] ml-0 lg:w-1/2 md:w-1/2 w-full'>
            <Image src={emqil} alt=''></Image>
        </div>
        <div className='lg:text-start md:text-start text-center lg:w-1/2 md:w-1/2 w-full mt-28 lg:ml-10 md:ml-10 ml-0'>
        <div className='flex'>
        <hr className='bg-[#D9D1F2] w-[100px] h-[7px] mt-2 rounded'/><span className='text-[18px] font-bold ml-4 font-apple text-[#3734A9]'>OUR SERVICES</span>
        </div>
        <h1 className='lg:text-[48px] md:text-[48px] text-[30px] font-medium text-[#220C60] font-apple'>Send Money To an<br />Email Address</h1>
        <p className='text-[16px] text-[#525254] font-normal mt-3'>Send money to any email address through Vividpay at no cost.<br />It is completely free.</p>
        <Link href='/auth/signup' passHref><div className='flex mt-6 w-[200px] h-[45px] font-[700] bg-[#3813A0] hover:bg-[#220C60] rounded-md
         text-[white] p-3 font-apple'>
          <button className='mr-4'>Get Started</button><Image src={icon} alt='' className='w-auto transition-all duration-1000 hover:translate-x-6'></Image>
        </div></Link>
      </div>
      </div>
      <div className='lg:flex md:flex block bg-new lg:mt-32 md:mt-32 mt-0 lg:p-0 md:p-0 p-2'>
      <div className='lg:text-start md:text-start text-center lg:w-1/2 md:w-1/2 w-full mt-28  lg:ml-[200px] md:ml-[200px] ml-0'>
        <div className='flex'>
        <hr className='bg-[#D9D1F2] w-[100px] h-[7px] mt-2 rounded'/><span className='text-[18px] font-bold ml-4 font-apple text-[#3734A9]'>OUR SERVICES</span>
        </div>
        <h1 className='lg:text-[48px] md:text-[48px] text-[30px] font-medium text-[#220C60] font-apple'>Airtime to Cash</h1>
        <p className='text-[16px] text-[#525254] font-normal mt-3'>Ever had too much airtime and would prefer to have cash instead? Airtime to Cash is the perfect solution for you. We buy airtime 24/7, so you never have to worry.</p>
        <Link href='/auth/signup' passHref><div className='flex mt-6 w-[200px] h-[45px] font-[700] bg-[#3813A0] hover:bg-[#220C60] rounded-md
         text-[white] p-3 font-apple'>
          <button className='mr-4'>Get Started</button><Image src={icon1} alt='' className='w-auto transition-all duration-1000 hover:translate-x-6'></Image>
        </div></Link>
      </div>
        <div className='bg-[#EBFBFF] text-center pt-16 pl-16 pr-16 pb-0 rounded-[40px] lg:mr-[200px] md:mr-[200px] mr-0 lg:w-1/2 md:w-1/2 w-full lg:mt-0 md:mt-0 mt-10'>
            <Image src={airtime} alt=''></Image>
        </div>
        
      </div>
      {/* other products */}
      <div className='bg-[#FFF7F2] mt-20 pt-20 pb-20'>
      <div className='lg:flex md:flex block lg:ml-[435px] md:ml-[435px] ml-0 text-center lg:text-start md:text-start'>
        <hr className='bg-[#D9D1F2] w-[100px] h-[7px] mt-2 rounded hidden lg:inline md:inline'/><span className='text-[18px] font-bold ml-4 font-apple text-[#3734A9]'>OUR SERVICES</span>
      </div>
        <h2 className='text-center md:text-[48px] lg:text-[48px] text-[28px] text-[#220C60] font-medium font-apple'>And So Much More......</h2>
      <section className='lg:flex md:flex block'>
        <div className='lg:ml-[100px] md:ml-[100px] ml-0 lg:mt-[200px] md:mt-[200px] mt-[50px] text-center lg:text-start md:text-start p-4 lg:p-0 md:p-0' id='one'>
          <div id='1-1'>
         <h3 className='text-[22px] text-[#220C60] font-medium font-apple'>Airtime to Cash</h3>
         <p className='text-[16px] text-[#525254] font-normal font-apple mt-2'>Sell your airtime and get cash or buy airtime</p>
         <Link href='/auth/signup' passHref className='flex mt-2'><p className='mr-4 text-[16px] text-[#3813A0] font-semibold font-apple'>Get Started</p>  <Image src={icon2} alt='' className='w-auto transition-all duration-1000 hover:translate-x-6'></Image></Link>
        </div>
        <div className='mt-10' id='1-2'>
        <h3 className='text-[22px] text-[#220C60] font-medium font-apple'>Cashpin</h3>
         <p className='text-[16px] text-[#525254] font-normal font-apple mt-2'>Cashpin is a token that can be saved as cash</p>
         <Link href='/auth/signup' passHref className='flex mt-2'><p className='mr-4 text-[16px] text-[#3813A0] font-semibold font-apple'>Get Started</p>  <Image src={icon2} alt='' className='w-auto transition-all duration-1000 hover:translate-x-6'></Image></Link>
        </div>
        <div className='mt-10' id='1-3'>
        <h3 className='text-[22px] text-[#220C60] font-medium font-apple'>Send Funds</h3>
         <p className='text-[16px] text-[#525254] font-normal font-apple mt-2'>Send money to an email address or any bank<br />account.</p>
         <Link href='/auth/signup' passHref className='flex mt-2'><p className='mr-4 text-[16px] text-[#3813A0] font-semibold font-apple'>Get Started</p>  <Image src={icon2} alt='' className='w-auto transition-all duration-1000 hover:translate-x-6'></Image></Link>
        </div>
        </div>
        <div id='two' className='w-[320px] mt-[50px] ml-[100px] hidden lg:inline md:inline'>
          <Image src={phoneIm} alt=''></Image>
        </div>
        <div className='lg:ml-[75px] md:ml-[75px] ml-0 lg:mt-[200px] md:mt-[200px] mt-[20px] text-center lg:text-start md:text-start p-4 lg:p-0 md:p-0' id='three'>
          <div id='1-1'>
         <h3 className='text-[22px] text-[#220C60] font-medium font-apple'>Fund Wallet</h3>
         <p className='text-[16px] text-[#525254] font-normal font-apple mt-2'>Fund your vividpay wallet and send money to<br />anyone.</p>
         <Link href='/auth/signup' passHref className='flex mt-2'><p className='mr-4 text-[16px] text-[#3813A0] font-semibold font-apple'>Get Started</p>  <Image src={icon2} alt='' className='w-auto transition-all duration-1000 hover:translate-x-6'></Image></Link>
        </div>
        <div className='mt-10' id='1-2'>
        <h3 className='text-[22px] text-[#220C60] font-medium font-apple'>Pay Bills</h3>
         <p className='text-[16px] text-[#525254] font-normal font-apple mt-2'>Pay electricity, TV subscription, data and<br />more bills.</p>
         <Link href='/auth/signup' passHref className='flex mt-2'><p className='mr-4 text-[16px] text-[#3813A0] font-semibold font-apple'>Get Started</p>  <Image src={icon2} alt='' className='w-auto transition-all duration-1000 hover:translate-x-6'></Image></Link>
        </div>
        </div>
      </section>
      </div>
      {/* Frequently asked question */}
      <div className='bg-[#D9D1F2] text-center p-10' id='faq'>
        <h1 className='text-[#220C60] font-bold font-apple lg:text-[48px] md:text[48px] text-[25px]'>Not Available Currently</h1>
      </div>
      {/* contact us section */}
      <div className='bg-[#FFF7F2] pt-14 pb-10' id='contact'>
         <h1 className='text-center text-[#220C60] lg:text-[56px] md:text-[56px] text-[40px] font-medium font-apple'>Contact Us</h1>
         <p className='text-center mt-6 font-apple text-[16px] text-[#525254] font-normal lg:p-0 md:p-0 p-1 mb-10'>
         Have a question or just want to say hi?<br />
         We d love to hear from you.
         </p>
         <div className='flex justify-center items-center lg:p-0 md:p-0 p-4'>
           <div className='bg-white lg:rounded-[30px] md:rounded-md rounded-lg lg:w-3/5 md:w-3/5 w-full pb-10'>
            <div className='mt-14 lg:flex md:flex block lg:justify-center lg:items-center md:justify-center md:items-center lg:p-0 md:p-4 p-4'>
             <input type="text" placeholder='Your Full Name' className='lg:w-2/5 md:w-full w-full border-[2px] border-[#D2D1D1] pl-3 focus:outline-[#D2D1D1] h-14'/>
             <input type="text" placeholder='Your Email Address' className='lg:w-2/5 md:w-full w-full border-[2px] border-[#D2D1D1] pl-3 focus:outline-[#D2D1D1] lg:ml-4 md:ml-0 ml-0 lg:mt-0 md:mt-4 mt-4 h-14'/>
            </div>
            <div className='mt-8 flex justify-center items-center lg:p-0 md:p-0 p-4'>
            <textarea name="message" id="message" cols={90} rows={8} className="border-[2px] border-[#D2D1D1] pl-3 pt-3 focus:outline-[#D2D1D1]" placeholder='Write Your Message'></textarea>
            </div>
            <div className='mt-6 text-center'>
            <Link href='/'><button className='w-[200px] h-[45px] font-[700] bg-[#3813A0] hover:bg-[#220C60] rounded-md text-[white]'>Submit</button></Link>
            </div>
           </div>
         </div>
      </div>
      <Footer/>
      </main>
    </>
  )
}
