import React, { useState } from 'react'
import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import iconb from "../../public/images/svgexport-14.svg"
import Headers from '@/components/header.tsx/headers';
const index = () => {
    const new_date :Date= new Date()
    const date : number = new_date.getDate()
    const year : number = new_date.getFullYear()
  // const [date, setdate]= useState(Date())
  console.log(date,year)
  return (
    <>
     <Head>
     <title>Vividpay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
     </Head>
      <main>
        <section className='w-full h-full bg-black'>  
        <Headers/>
        <div>
          davido1000
        </div>
        </section>
      </main>
    </>
  )
}

export default index;