import React, { useState,useEffect } from 'react'
import Head from 'next/head';
import Image from 'next/image';
import iconb from "../../public/images/svgexport-14.svg"
import Headers from '@/components/header.tsx/headers';
import people from "../../public/images/profile-pic.a9136072d073801df253.png"
import axios from 'axios';
import { useRouter } from 'next/router';
import SideBar from '@/components/home/sidebar';
import ThirdBar from '@/components/home/thirdbar';
import Funding from '../modals/funding';
import EnterpinAirtime from '../modals/airtimemodal/enterpin';
import Info from '../modals/info';
import dstv from "../../public/images/DStv_Logo_2012.png"
import gotv from "../../public/images/GoTv.png"
import startimes from "../../public/images/startimes-logo.png"
import { AiOutlineArrowRight } from 'react-icons/ai'
import Dstv from '../modals/billsFolder/dstv';
const PayBills = () => {
    // dstv states
    const [isDstvOpen, setIsDstvOpen]= useState<boolean>(false);
    const [pinOpen, setPinOpen] = useState<boolean>(false);
    const [pinDone, setpinDone] = useState<boolean>(false);
   // dstv function
    const handleDstvOpen=()=>{
        setIsDstvOpen(true);
    }
    const handleDstvClose=()=>{
        setIsDstvOpen(false);
        setPinOpen(true);
    }
    const closePinModal=()=>{
        setPinOpen(false);
        setpinDone(true)
    }

  return (
    <>
     <Head>
       <title>Pay Bills - Vividpay</title>
       <meta name="description" content="Generated by create next app" />
       <meta name="viewport" content="width=device-width, initial-scale=1" />
       <link rel="icon" href="/favicon.ico" /> 
    </Head>
    <main>
       <section className='w-full h-full bg-[#F1F1F1] pb-5'>  
       <Headers/>
       <div className='lg:flex md:block block'>
        <div className='lg:hidden md:flex flex md:items-center items-center md:mt-5 mt-5 md:ml-[5%] ml-[5%]'>
        <div className='mr-3'>
           <Image src={people} alt="" width={40} className='rounded-full'/>
         </div>
         <div className=''>
           <p className='text-[#535355] font-medium font-sans text-[14px]'>Hi, olu</p>
         </div>
        </div>
         {/* sidebar menu code */}
          <SideBar/>
       {/* middle account info code */}
       <div  id='two' className='lg:mt-[2%] lg:w-[53%] lg:h-[600px] lg:ml-[2.3%] md:mt-[2%] md:w-[90%] md:h-[700px]  md:ml-[5%] mt-[2%] w-[90%] ml-[5%] h-[500px] rounded-xl flex justify-center flex-col items-center'>
            <div className='bg-white lg:w-[50%] md:w-[90%] w-[90%] h-[50px] mb-5 flex justify-center items-center rounded-xl shadow-sm'>
            <h1 className='text-[26px] font-apple  font-medium'>Pay Bills</h1>
            </div>
          <div className='w-[100%] flex justify-center items-center flex-col'>
            {/* //dstv */}
            <div className='bg-white lg:w-[50%] md:w-[90%] w-[90%] h-[80px] shadow-sm mb-5 cursor-pointer flex items-center justify-between pl-6 pr-6 rounded-xl' onClick={handleDstvOpen}>
            <div className='flex items-center' >
             <Image src={dstv} alt='vividpaylogo' width={40}/>
             <p className='text-center ml-3 font-medium text-[19px]'>DSTV</p>
            </div>
            <AiOutlineArrowRight className='text-[25px]'/>
            </div>
            {/* gotv */}
            <div className='bg-white lg:w-[50%] md:w-[90%] w-[90%] h-[80px] shadow-sm mb-5 cursor-pointer flex items-center justify-between pl-6 pr-6 rounded-xl' >
            <div className='flex items-center'>
            <Image src={gotv} alt='vividpaylogo' width={40}/>
             <p className='text-center ml-3 font-medium text-[19px]'>GOTV</p>
            </div>
            <AiOutlineArrowRight className='text-[25px]'/>
            </div>
            {/* startimes */}
            <div className='bg-white lg:w-[50%] md:w-[90%] w-[90%] h-[80px] shadow-sm mb-5 cursor-pointer flex items-center justify-between pl-6 pr-6 rounded-xl'>
            <div className='flex items-center'>
            <Image src={startimes} alt='vividpaylogo' width={40}/>
             <p className='text-center ml-3 font-medium text-[19px]'>Startimes</p>
            </div>
            <AiOutlineArrowRight className='text-[25px]'/>
            </div>
          </div>
          {isDstvOpen && <div className="fixed inset-0 bg-gray-800 opacity-50"></div>}
          <Dstv isOpen={isDstvOpen} onClose={handleDstvClose} setIsDstvOpen={setIsDstvOpen}/>
          <EnterpinAirtime isOpen={pinOpen} setPinOpen={setPinOpen} onClose={closePinModal}/>
          <Info setpinDone={setpinDone} isOpen={pinDone} pinDone={pinDone}/>
        </div>
         {/* {third section of dashboard} */}
        <ThirdBar/>
       </div>
       </section>
     </main>
    </>
  )
}

export default PayBills;