import React, { useState,useEffect } from 'react'
import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import Headers from '@/components/header.tsx/headers';
import people from "../../public/images/profile-pic.a9136072d073801df253.png"
import axios from 'axios';
import { useRouter } from 'next/router';
import SideBar from '@/components/home/sidebar';
import ThirdBar from '@/components/home/thirdbar';
import logo  from "../../public/favicon.ico"
import { AiOutlineArrowRight } from 'react-icons/ai'
import { AiFillBank } from 'react-icons/ai'
import OpenVivid from '../modals/sendMoneyModal/openvivid';
import Enterpin from '../modals/sendMoneyModal/enterpin';
const Sendmoney = () => {
    const [isVividOpen, setisVividOpen] = useState<boolean>(false);
    const [sending, setSending] = useState<boolean>(false);
    const [pinOpen, setpinOpen] = useState<boolean>(false);
    const handleVividModal = () => {
        setisVividOpen(true);
      };
    
      const handleVividClose = () => {
        setisVividOpen(false);
      };
  return (
    <>
      <Head>
       <title>Send Wallet - Vividpay</title>
       <meta name="description" content="Generated by create next app" />
       <meta name="viewport" content="width=device-width, initial-scale=1" />
       <link rel="icon" href="/favicon.ico" /> 
    </Head>
    <section className='w-full h-full bg-[#F1F1F1] pb-5'>
        <Headers/>
        <div className='lg:flex md:block block'>
        <div className='lg:hidden md:flex flex md:items-center items-center md:mt-5 mt-5 md:ml-[5%] ml-[5%]'>
        <div className='mr-3'>
           <Image src={people} alt="" width={40} className='rounded-full'/>
         </div>
         <div className=''>
           <p className='text-[#535355] font-medium font-sans text-[14px]'>Hi, olu</p>
         </div>
        </div>
        {/* sidebar menu code */}
        <SideBar/>
        {/*midddle account info*/}
        <div  id='two' className='lg:mt-[2%] lg:w-[53%] lg:h-[600px] lg:ml-[2.3%] md:mt-[2%] md:w-[90%] md:h-[700px]  md:ml-[5%] mt-[2%] w-[90%] ml-[5%] h-[500px] rounded-xl flex justify-center flex-col items-center'>
            <div className='bg-white lg:w-[50%] md:w-[90%] w-[90%] h-[50px] mb-5 flex justify-center items-center rounded-xl shadow-sm'>
            <h1 className='text-[26px] font-apple  font-medium'>Send Money</h1>
            </div>
          <div className='w-[100%] flex justify-center items-center flex-col'>
            {/* //to vividpay */}
            <div className='bg-white lg:w-[50%] md:w-[90%] w-[90%] h-[80px] shadow-sm mb-5 cursor-pointer flex items-center justify-between pl-6 pr-6 rounded-xl' onClick={handleVividModal}>
            <div className='flex items-center' >
             <Image src={logo} alt='vividpaylogo' width={40}/>
             <p className='text-center ml-3 font-medium text-[19px]'>To VividPay</p>
            </div>
            <AiOutlineArrowRight className='text-[25px]'/>
            </div>
            {/* to other banks */}
            <div className='bg-white lg:w-[50%] md:w-[90%] w-[90%] h-[80px] shadow-sm mb-5 cursor-pointer flex items-center justify-between pl-6 pr-6 rounded-xl'>
            <div className='flex items-center'>
             <AiFillBank className='text-[40px] text-[#9672FF]'/>
             <p className='text-center ml-3 font-medium text-[19px]'>To Other Banks</p>
            </div>
            <AiOutlineArrowRight className='text-[25px]'/>
            </div>
            {/* to prepaid account */}
            <div className='bg-white lg:w-[50%] md:w-[90%] w-[90%] h-[80px] shadow-sm mb-5 cursor-pointer flex items-center justify-between pl-6 pr-6 rounded-xl'>
            <div className='flex items-center'>
            <AiFillBank className='text-[40px] text-[#9672FF]'/>
             <p className='text-center ml-3 font-medium text-[19px]'>To Prepaid Accounts</p>
            </div>
            <AiOutlineArrowRight className='text-[25px]'/>
            </div>
          </div>
          {isVividOpen && <div className="fixed inset-0 bg-gray-800 opacity-50"></div>}
          <OpenVivid isOpen={isVividOpen} onClose={handleVividClose} setVivid={setisVividOpen} pinOpen={pinOpen} setpinOpen={setpinOpen}/>
          <Enterpin isOpen={pinOpen} setpinOpen={setpinOpen}/>
        </div>
         {/* {third section of dashboard} */}
         <ThirdBar/>
       </div>
    </section>
    </>
  )
}

export default Sendmoney