import React, { useState,useEffect } from 'react'
import Head from 'next/head';
import Image from 'next/image';
import iconb from "../../public/images/svgexport-14.svg"
import Headers from '@/components/header.tsx/headers';
import people from "../../public/images/profile-pic.a9136072d073801df253.png"
import axios from 'axios';
import { useRouter } from 'next/router';
import SideBar from '@/components/home/sidebar';
import ThirdBar from '@/components/home/thirdbar';
const Wallet = () => {
  // for creating new wallet
  const [isNewWalletOpen, setisNewWalletOpen] = useState<boolean>(false)
  const [pinOpen, setpinOpen] = useState<boolean>(false);
  const [info, setinfo] = useState<boolean>(false);
  return (
    <>
      <Head>
       <title>Wallets - Vividpay</title>
       <meta name="description" content="Generated by create next app" />
       <meta name="viewport" content="width=device-width, initial-scale=1" />
       <link rel="icon" href="/favicon.ico" /> 
    </Head>
    <main>
        <section className='w-full h-full bg-[#F1F1F1] pb-5'>
        <Headers/>
        <div className='lg:flex md:block block'>
        <div className='lg:hidden md:flex flex md:items-center items-center md:mt-5 mt-5 md:ml-[5%] ml-[5%]'>
        <div className='mr-3'>
           <Image src={people} alt="" width={40} className='rounded-full'/>
         </div>
         <div className=''>
           <p className='text-[#535355] font-medium font-sans text-[14px]'>Hi, olu</p>
         </div>
        </div>
        {/*sidebar menu code*/}
        <SideBar/>
        {/* middle account info code */}
        <div  id='two' className='lg:mt-[2%] lg:w-[53%] lg:h-[600px] lg:ml-[2.3%] md:mt-[2%] md:w-[90%] md:h-[700px]  md:ml-[5%] mt-[2%] w-[90%] ml-[5%] h-[500px] rounded-xl flex flex-col items-center'>
        <div className='w-[80%] flex justify-between'>
          <h1 className='text-[36px] font-apple font-medium'>Wallet</h1>
          <button className='block lg:w-[20%] md:w-[40%] w-[40%] h-[55px] bg-[#623ECA] rounded-[4px] text-[#FFFFFF] text-[18px] font-semibold font-sans'>Add Wallet</button>
        </div>
        {/* displayer of available wallets */}
        <div className='mt-[150px]'>
          <p className='text-[26px] font-apple font-medium'>No available Wallets</p>
        </div>
        </div>
        {/* {third section of dashboard} */}
        <ThirdBar/>
        </div>
        </section>
    </main>
    </>
  )
}

export default Wallet